version: 2.1
orbs:
  pypi: pennlabs/pypi-tools@0.0.4
workflows:
  build-and-publish:
    jobs:
      - pypi/test:
          filters:
            tags:
              only: /.*/
      - pypi/publish:
          context: PYPI
          filters:
            branches:
              only: master
            tags:
              only: '/[0-9]+(\.[0-9]+)*/'
          requires:
            - pypi/test
